### ISSUE TITLE
Wrong position in Lightning Experience

### ISSUE THREAD

**Issue by fracarma** [pozil/sfdc-ui-modal#1]
While the component is working well in VF, when I use it into another component in LEX I've got a wrong position:

![modalissue](https://cloud.githubusercontent.com/assets/12348998/25859376/a5b36108-34de-11e7-903d-4b649b7c4ab8.PNG)

If the content of the modal is too big, the scroll bar appears, but the maximum height is too much, I can't see the title. I understand that probably it's a SLDS issue, but maybe there could be some workaround.

**Comment by pozil** [comment]
Hi @fracarma,

This is indeed a SLDS issue so I cannot do much to fix it.
The workaround for this is to use a [vertical scrollable zone](https://www.lightningdesignsystem.com/components/utilities/scrollable/#flavor-vertical).

Cheers,

**Comment by fracarma** [comment]
Thanks!
