### ISSUE TITLE
Clear Modal input fileds

### ISSUE THREAD

**Issue by mingworld** [pozil/sfdc-ui-modal#2]
Hi,

I use this ui-modal lightning components as data entry form. Once button confirm is clicked, the data is saved and modal form is closed. but when click open modal again, old data are still on the input fields (number type). I try to reset binding attribute and it is not working.

What is the best way to clear input fields (number types) on this modal form.

Thanks for your help.

**Comment by pozil** [comment]
There are two answers to your question depending on whether you are using a static or dynamic modal.

**Static modal**
For a static modal, I only use CSS to show/hide the modal so if you leave some data in your form it will still be the same when you re-open the modal.

You need to ensure that the form values are initialized/reset before calling:
`component.find("theStaticModal").openModal();`.

**Dynamic modal**
You can create the modal and it's child components (the form) from scratch each time before you open them with `$A.createComponent(...)`.
If you do that you will also need to destroy the component afterwards with `component.destroy()`.

**Comment by mingworld** [comment]
Thanks for your help. Your modal lighting component works great! Thanks so much for sharing it.

I am using static modal. I tried to reset before calling component.find("theStaticModal").openModal();
but it did not work for "number" type of lightning:input.
Here is my lightning:input component

<lightning:input class="slds-form-element slds-size_1-of-3" type="number" label="Current value" name="Model" formatter="currency" value="{!v.newInvestmentProperty.CurrentValue__c}" />

I can reset it to "0", but I can't reset it to a blank field. I know this is got nothing to do with your modal component. I am justing wondering if you know a way to reset lightning:input (number type) to blank?

Thanks

**Comment by pozil** [comment]
Hi Ming,

To reset it, I would assign `null` to its value since the `Number` type supports it.
However, I just tried that but the widget is not updated in that case.
This could be a bug on the `lightning:input` component.

I am sorry but I don't have any alternative to propose.

Cheers,

**Comment by mingworld** [comment]
Thanks for your help! 
I tried to set its value to 'null' and '' and none of them worked. I had to set to 0. It is not nice but it is an okay walkaround.

**Comment by pozil** [comment]
@mingworld I can confirm that this is a bug.
I reported it to the lightning team.

**Comment by mingworld** [comment]
@pozil Thank you!
